version: '3'
services:
  frontend:
    build:
      context: ../
      dockerfile: trippin-docker/frontend/Dockerfile
    ports:
      - "80:80"
    networks:
      - trippin-net
  backend:
    build:
      context: ../trippin-backend
      dockerfile: ../trippin-docker/backend/Dockerfile
    ports:
      - "3009:3009"
    environment:
      MONGO_URI: mongodb://mongodb:27017/trippin
    depends_on:
      - mongodb
    networks:
      - trippin-net
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - trippin-net
  ngrok:
    image: wernight/ngrok
    command: sh -c "ngrok http backend:3009"
    ports:
      - "4040:4040"
    networks:
      - trippin-net

networks:
  trippin-net: